package com.wisetasklecturer.entities;

public enum AssessmentType {

	ASSESSED_LAB, DEBATE, DEMO_TEACHING, FINAL_EXAM, ORAL_EXAMINATION, PORTFOLIO,
	PRESENTATION, PROJECT, QUIZ, REPORT, SELF_REFLECTION, OTHER;
	
}